name: april_assets_hide
description: A new Flutter project.
version: 1.0.1
author: 'AAAAAApril'
homepage: 'https://github.com/AAAAAApril/AssetsHide'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  # https://pub.flutter-io.cn/packages/path
  path: ^1.8.0
  # https://pub.flutter-io.cn/packages/yaml
  yaml: ^3.1.0

dev_dependencies:
  # https://pub.flutter-io.cn/packages/build_runner
  build_runner: ^2.0.4